version: "3.7"

services:
  mysql:
    container_name: catalog-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_DATABASE=catalog
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - catalog-network

networks:
  catalog-network:
